#include "Channel/Channel.h"
#include "Channel/EventArgs/ChannelCreateEventArgs.h"
#include "Channel/EventArgs/ChannelDeleteEventArgs.h"
#include "Channel/EventArgs/ChannelPinsUpdateEventArgs.h"
#include "Channel/EventArgs/ChannelUpdateEventArgs.h"

#include "Guild/Guild.h"
#include "Guild/EventArgs/GuildBanAddEventArgs.h"
#include "Guild/EventArgs/GuildBanRemoveEventArgs.h"
#include "Guild/EventArgs/GuildCreateEventArgs.h"
#include "Guild/EventArgs/GuildDeleteEventArgs.h"
#include "Guild/EventArgs/GuildEmojisUpdateEventArgs.h"
#include "Guild/EventArgs/GuildIntegrationsUpdateEventArgs.h"
#include "Guild/EventArgs/GuildMemberAddEventArgs.h"
#include "Guild/EventArgs/GuildMemberRemoveEventArgs.h"
#include "Guild/EventArgs/GuildMemberUpdateEventArgs.h"
#include "Guild/EventArgs/GuildRoleCreateEventArgs.h"
#include "Guild/EventArgs/GuildRoleDeleteEventArgs.h"
#include "Guild/EventArgs/GuildRoleUpdateEventArgs.h"
#include "Guild/EventArgs/GuildUpdateEventArgs.h"

#include "Message/Message.h"
#include "Message/EventArgs/MessageBulkDeleteEventArgs.h"
#include "Message/EventArgs/MessageCreateEventArgs.h"
#include "Message/EventArgs/MessageDeleteEventArgs.h"
#include "Message/EventArgs/MessageReactionAddEventArgs.h"
#include "Message/EventArgs/MessageReactionRemoveEmojiEventArgs.h"
#include "Message/EventArgs/MessageReactionRemoveEventArgs.h"
#include "Message/EventArgs/MessageReactionsClearEventArgs.h"
#include "Message/EventArgs/MessageUpdateEventArgs.h"

#include "Emoji/Emoji.h"
#include "Emoji/EventArgs/EmojiEventArgs.h"

#include "Embed/Embed.h"